function [ac, feasible] = check_feasible_sizing_TS(ac)

sizing_plot_driver_ref;

WSdesign = ac.a2a.W0 ./ ac.initial.Sref .* 0.020885434273039;
TWmax = ac.initial.T_max./ac.a2a.W0;
TWmil = ac.initial.T_mil./ac.a2a.W0;

feasible = true;
if WSdesign >= min([WS_a2a_max_g, WS_a2a_landing, max(WS_a2a_catapult), WS_a2a_recovery])
    feasible = false;
end
if TWmax <= max([interp1(WS2, TW_a2a_dash, WSdesign, "linear") ...
                 interp1(WS2, TW_a2a_turn_rate, WSdesign, "linear") ...
                 interp1(WS2, TW_a2a_cruise_1, WSdesign, "linear") ...
                 interp1(WS2, TW_a2a_cruise_2, WSdesign, "linear") ...
                 interp1(WS2, TW_a2a_ceiling, WSdesign, "linear") ...
                 interp1(WS2, TW_a2a_climb_to, WSdesign, "linear") ...
                 interp1(WS2, TW_a2a_climb_ap, WSdesign, "linear") ...
                 interp1(WS2, TW_a2a_climb_1, WSdesign, "linear") ...
                 interp1(WS2, TW_a2a_climb_2, WSdesign, "linear") ...
                 interp1(WS2, TW_a2a_takeoff, WSdesign, "linear")])
    feasible = false;
end
if TWmil <= max([interp1(WS2, TW_a2a_cruise_1, WSdesign, "linear") ...
                 interp1(WS2, TW_a2a_cruise_2, WSdesign, "linear") ...
                 interp1(WS2, TW_a2a_climb_1, WSdesign, "linear") ...
                 interp1(WS2, TW_a2a_climb_2, WSdesign, "linear")])
    feasible = false;
end    
end